#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=10

start_service() {
	local interval
	interval="$(uci -q get rdzbridge.main.interval || echo 30)"
	procd_open_instance
	procd_set_param command /bin/sh -c "while true; do /usr/sbin/rdzbridge-watchdog; sleep $interval; done"
	procd_set_param respawn 3600 5 5
	procd_close_instance
}
