#!/bin/sh
HASH="$(awk -F: '$1 == "root" { print $2; exit }' /etc/shadow 2>/dev/null)"
case "$HASH" in
	''|'!'|'!!'|'*'|\!*|\**)
		echo '{"configured":false}'
		;;
	*)
		echo '{"configured":true}'
		;;
esac
